/* Table Loot Forge — description + lore pools */
(function(g){
const LOOK_GEAR={Weapon:["The blade catches torchlight with a restless gleam; the grip is worn smooth by unfinished stories."],Armor:["Plates (or layered hide) fit without squeal; dust in the seams glitters like powdered mica."],Shield:["The face is scarred by arrows that never found flesh; a painted emblem has half-flaked away."],Helmet:["The helm sits snug; padding smells of cedar and old smoke."],Cloak:["Heavy wool drapes with a soft hush; the hem is stained by roads not yet walked."],Necklace:["The pendant rests cold, then matches your warmth; chain links are uneven and handmade."],Ring:["The band is hammer-shaped, not mold-perfect; it slides on with quiet finality."],Gloves:["Leather creaks softly; knuckles are discreetly reinforced."],Belt:["The buckle is heavier than it looks; stitching is tight and proud."],Boots:["Soles are thick but quiet on stone; the uppers hug the ankle without biting."]};
const LOOK_SCROLL=["Rolled vellum tied with a faded ribbon; ink smells of iron and candle soot.","A lacquered scroll-case; glyphs shimmer when it opens."];
const LOOK_POTION=["Thick glass vial, cork wired shut; color ribbons swirl and never fully mix.","Stoppered brew catches light like gemstone dust in syrup."];
const LOOK_TINCTURE=["Slim dropper-vial; herbal sediment settles like green snow.","Wax-dipped neck; a cramped tag names the dose."];

/* —— Lore fragments: origin + rumor + quirk (compose 2–3 sentences) —— */
const LORE_ORIGIN=(()=>{const P=t=>t.split("|");const o={};o["_any"]=P("Forged in a roadside forge that vanished overnight.|Pulled from a chest that refused to stay shut.|Recovered from a flooded vault beneath a collapsed shrine.|Traded across three borders for a promise no one kept.|Commissioned by a captain who never returned from the last march.");o["Weapon"]=P("Quenched in rainwater collected on a battlefield.|Smith-blessed with a prayer that cuts both ways.|First swung in a duel that ended before blood hit the dust.");o["Armor"]=P("Fitted to a hero whose name the bards argue about.|Riveted under a blue moon by a guild that no longer exists.|Taken off a mannequin in a sealed armory.");o["Shield"]=P("Painted for a house whose banners burned last winter.|Carried through a siege that never made the histories.|Hung above a tavern hearth until the hearth went cold.");o["Helmet"]=P("Worn by a watch captain who saw too many dawns.|Pulled from a barrow where the dead slept lightly.|Cast from metal scrap of a fallen bell.");o["Cloak"]=P("Woven on a loom that only works in fog.|Stolen from a stage costume and never returned.|Dyed with ash from a city that rebuilt itself.");o["Necklace"]=P("Strung with beads from a river that changed course.|Blessed (or cursed) at a roadside shrine.|Last heirloom of a family that forgot its own crest.");o["Ring"]=P("Cut from a coin of a mint that never was.|Slipped onto a finger in a dream that left a mark.|Sealed a pact spoken in a language both parties pretended to know.");o["Gloves"]=P("Sewn for a climber who vanished mid-ascent.|Oiled with a recipe sold only at midnight markets.|Won in a wager over a locked door.");o["Belt"]=P("Buckle cast from a shattered sword.|Cinched a diplomat through three failed treaties.|Found coiled like a snake beside an empty camp.");o["Boots"]=P("Walked a pilgrimage route scrubbed from modern charts.|Resoled by a cobbler who charged in secrets.|Left outside a circle of standing stones at dawn.");o["Scroll"]=P("Copied by a scribe who refused to sleep until it was done.|Smuggled in a hollow bone past three checkpoints.|Ink mixed with ash from a burned spellbook.");o["Potion"]=P("Brewed in a copper still that sings when the moon is high.|Bottled during a thunderstorm that never touched the ground.|Recipe torn from a herbalist’s private ledger.");o["Tincture"]=P("Steeped from herbs gathered on the wrong side of a ward-line.|Measured drop by drop by an apothecary with shaking hands.|Labelled in a cipher only healers bother to learn.");return o;})();
const LORE_RUMOR=(()=>{const P=t=>t.split("|");const o={};o["_any"]=P("Locals claim it hums before storms.|A tavern rumor says three owners died smiling.|Street prophets say it chooses who may keep it.|Someone offered a kingdom’s ransom and left empty-handed.|A faded tag reads: return if you survive.");o["Common"]=P("Most folk shrug it off as junk with a story.|It turns up in pawn shops more often than it should.");o["Uncommon"]=P("Collectors quietly ask after pieces like this.|A guild apprentice swore it saved their life once.");o["Rare"]=P("Rumor puts a duke’s agent on the trail.|Temples debate whether to sanctify or sequester it.");o["Very Rare"]=P("Whole companies have broken apart arguing over who should carry it.|A sage’s letter warns: power this deep leaves fingerprints on fate.");o["Legendary"]=P("Prophecies mention something that matches this description too closely.|Kings have started wars for less — and ended them for the same.");return o;})();
const LORE_QUIRK=(()=>{const P=t=>t.split("|");const o={};o["_any"]=P("Still warm, as if it remembers the last fight.|Smells faintly of rain on hot iron.|The maker’s mark is a coin with no mint.|Blessed by someone who no longer believes in gods.|Scratched with traveler’s tally marks — none recent.");o["Weapon"]=P("The edge never dulls in story — only in practice, stubbornly.|It rings a clear note when drawn near lies.");o["Armor"]=P("Joints never squeak, even after mud and salt.|Wearers report dreams of standing watch.");o["Shield"]=P("Arrows that miss leave no scratch on the paint.|It feels lighter when raised for someone else.");o["Helmet"]=P("Whispers of wind inside even on still days.|You notice more exits than you used to.");o["Cloak"]=P("Hem never quite gets soaked through.|Shadows linger a second longer beneath it.");o["Necklace"]=P("Pulse in the pendant syncs with yours after a minute.|It grows faintly warm near betrayal.");o["Ring"]=P("Turns itself slightly when danger approaches.|Leaves a pale band that fades slowly.");o["Gloves"]=P("Fingertips tingle before a climb or a catch.|They never fully dry after rain — and never mildew.");o["Belt"]=P("Buckle warms when you steel yourself to speak.|Pouches seem to hold one extra coin overnight.");o["Boots"]=P("Steps sound softer to enemies than to friends.|They always find the dry path through dew.");o["Scroll"]=P("Ink rearranges if you look away too long.|The case refuses to open for the unworthy — or the impatient.");o["Potion"]=P("Sediment forms a tiny constellation, then dissolves.|Uncorked, candles nearby lean toward it.");o["Tincture"]=P("One drop stains cloth the color of new leaves.|The taste is gone before you can name it.");return o;})();
g.TLF_LOOK_GEAR=LOOK_GEAR;g.TLF_LOOK_SCROLL=LOOK_SCROLL;g.TLF_LOOK_POTION=LOOK_POTION;g.TLF_LOOK_TINCTURE=LOOK_TINCTURE;
g.TLF_LORE_ORIGIN=LORE_ORIGIN;g.TLF_LORE_RUMOR=LORE_RUMOR;g.TLF_LORE_QUIRK=LORE_QUIRK;
})(typeof window!=="undefined"?window:globalThis);
