(function(){
const R=["Common","Uncommon","Rare","Very Rare","Legendary"];
const T=["Weapon","Armor","Shield","Helmet","Cloak","Necklace","Ring","Gloves","Belt","Boots","Scroll","Potion","Tincture"];
const RC={Common:"rarity-common",Uncommon:"rarity-uncommon",Rare:"rarity-rare","Very Rare":"rarity-veryrare",Legendary:"rarity-legendary"};
const S={Common:{b:0,dc:11,d:"1d4",D:"1d6",u:"1/day",a:.05,sp:"cantrip"},Uncommon:{b:1,dc:13,d:"1d6",D:"2d6",u:"1/day",a:.35,sp:"1st–2nd"},Rare:{b:1,dc:15,d:"2d6",D:"3d6",u:"2/day",a:.75,sp:"3rd–4th"},"Very Rare":{b:2,dc:16,d:"3d6",D:"4d8",u:"3/day",a:.9,sp:"5th–6th"},Legendary:{b:3,dc:18,d:"4d6",D:"6d8",u:"at will",a:1,sp:"7th–9th"}};
const ADJ="Ashen Bright Cinder Crimson Dawn Dusk Ember Feral Frost Gilded Hollow Iron Jade Keen Lunar Mist Obsidian Quiet Riven Rune Scarlet Shadow Silver Storm Thorn Verdant Warden Wild Zephyr Blight Elder Glimmer Hearth Ivory Nettle Oaken Prism Quicksilver".split(" ");
const DMG="fire cold lightning thunder acid poison necrotic radiant force psychic".split(" ");
const SK="Stealth Athletics Acrobatics Perception Insight Survival Intimidation Persuasion Arcana".split(" ");
const SV="Strength Dexterity Constitution Intelligence Wisdom Charisma".split(" ");
const LORE=["Forged in a roadside forge that vanished overnight.","Still warm, as if it remembers the last fight.","Smells faintly of rain on hot iron.","Pulled from a chest that refused to stay shut.","Locals claim it hums before storms.","Traded for a secret that wasn’t worth keeping.","A faded tag reads: return if you survive.","The maker’s mark is a coin with no mint.","Blessed by someone who no longer believes in gods.","Found wrapped in a map that leads nowhere useful.","A tavern rumor says three owners died smiling.","Scratched with traveler’s tally marks — none recent."];
const N={Weapon:"Blade Cleaver Fang Flail Glaive Hammer Lance Mace Pike Razor Saber Spear Sword Talon Brand Dirk Hatchet Maul Scythe Sting".split(" "),Armor:"Aegis Carapace Cuirass Harness Mail Plate Shell Vest Ward Jacket Coat Hauberk Scale".split(" "),Shield:"Bulwark Guard Aegis Barrier Buckler Rampart Ward Targe Plate Door".split(" "),Helmet:"Helm Crown Circlet Mask Visor Diadem Casque Browguard Cowl-helm Hood-cap".split(" "),Cloak:"Cloak Mantle Shawl Cape Wrap Drape Veil Tabard Shroud Poncho".split(" "),Necklace:"Amulet Pendant Torc Choker Locket Talisman Collar Medallion Charm Sigil".split(" "),Ring:"Band Ring Loop Seal Signet Hoop Coil Wheel Knot".split(" "),Gloves:"Gloves Gauntlets Grips Mitts Handwraps Claws Fists Palms".split(" "),Belt:"Belt Sash Girdle Cincture Cord Waistband Strap Cinch Baldric".split(" "),Boots:"Boots Greaves Treads Sandals Striders Steps Soles Pathfinders Spurs".split(" ")};
const SL={Weapon:"Weapon",Armor:"Armor",Shield:"Shield",Helmet:"Head",Cloak:"Shoulders",Necklace:"Neck",Ring:"Ring",Gloves:"Hands",Belt:"Waist",Boots:"Feet"};
const pick=a=>a[Math.floor(Math.random()*a.length)];
const chance=p=>Math.random()<p;
const fill=(t,m)=>t.replace(/\{(\w+)\}/g,(_,k)=>m[k]!=null?m[k]:"{"+k+"}");
function nameOf(type){const a=pick(ADJ),n=pick(N[type]);return pick([a+" "+n,n+" of the "+a,"The "+a+" "+n,pick(ADJ)+" "+a+" "+n]);}
function attune(r,s){if(chance(s.a))return " Requires attunement.";if(["Rare","Very Rare","Legendary"].includes(r)&&chance(.4))return " Requires attunement.";return "";}
function gearFx(type,r,s){
  const t=pick(DMG),sk=pick(SK),sv=pick(SV),{b,dc,d,D,u}=s;
  const str={Common:13,Uncommon:15,Rare:17,"Very Rare":19,Legendary:21}[r];
  const P={
    Weapon:["Weapon (any proficient). +{b} attack & damage. Once/turn on hit: extra {d} {t}.","Weapon. +{b} attack. Crit: prone (DC {dc} Str negates).","Weapon. +{b} damage. Bonus action {u}: next hit +{D} {t}.","Weapon. Crit 19–20. Hit {u}: DC {dc} Con or no reactions until your next turn.","Thrown 20/60 + normal properties. +{b} attack; returns after throw.","Weapon. +{b} attack. Ignore half cover."],
    Armor:["Armor (pick light/medium/heavy). +{b} AC. {u}: resist {t} 1 min.","Armor. +{b} AC. Advantage on death saves.","Armor. +{b} AC. Melee attacker takes {d} {t} ({u}).","Armor. +{b} AC. Don/doff as an action."],
    Shield:["Shield. +{b} AC (stacks with +2). Reaction {u} when hit: +2 AC vs that attack.","Shield. Resist {t}. Bash: {d} bludgeoning ({u}).","Shield. +{b} AC. Allies within 5 ft +1 AC vs ranged.","Shield. {u}: 10-ft line; DC {dc} Str or pushed 10 ft & prone."],
    Helmet:["Head. +{b} {sk}. Darkvision 60 ft (or +30).","Head. Advantage vs charmed. {u}: end frightened.","Helm. Can’t be surprised while conscious. +{b} Perception (sight).","Circlet. {u}: detect thoughts (DC {dc}), conc. 1 min."],
    Cloak:["Shoulders. Advantage on Stealth. {u}: mist lightly obscures you 1 min.","Cloak. +{b} AC or saves (DM picks one). Resist {t}.","Mantle. {u}: leave no tracks 10 min.","Cloak. {u} when hit by ranged: miss instead."],
    Necklace:["Neck. +{b} {sv} saves.","Amulet. {u}: heal {D} HP (not above half max).","Pendant. Breathe water; advantage vs inhaled poison.","Talisman. {u}: sanctuary (DC {dc})."],
    Ring:["Ring. +{b} spell attacks/DCs — or +{b} to one ability check.","Ring. {u}: misty step.","Ring. Resist {t}. {u}: ignore that type until your next turn.","Band. {u} on a failed save: reroll it."],
    Gloves:["Hands. +{b} Athletics; climb = walk speed.","Gauntlets. Unarmed {d} bludgeoning (magical), +{b} hit.","Gloves. {u}: mage hand (20 lb, 1 min).","Grips. Advantage to keep hold; can’t be disarmed ({u} if contested)."],
    Belt:["Waist. Strength {str} (or +2 if higher — DM).","Belt. {u}: Dash as bonus action.","Girdle. Double carry; advantage vs shove/prone.","Sash. {u}: when you spend a Hit Die, extra {D} HP."],
    Boots:["Feet. +10 ft speed; ignore nonmagical difficult terrain.","Boots. {u}: triple jump; landing doesn’t provoke this turn.","Treads. Walk on water/soft ground.","Striders. Climb free. {u}: spider climb 10 min."]
  };
  if(type==="Weapon"&&(r==="Very Rare"||r==="Legendary"))P.Weapon.push("Weapon. +{b} attack/damage. {u}: 30-ft cone {t}; DC {dc} Dex, {D} {t} (half on success).");
  let m=fill(pick(P[type]),{b:b||0,d,D,t,dc,u,sk,sv,str});
  if(!b)m=m.replace(/\+0 /g,"no bonus ");
  return m+attune(r,s);
}
const SCR={
  cantrip:[["Sparkneedle","Cantrip. Ranged spell attack 60 ft; {d} piercing + {d} {t}."],["Dustwhisper","Cantrip. DC {dc} Wis or disadvantage on next attack."],["Pebbleward","Cantrip. Touch: +2 AC vs next attack."],["Inkblink","Cantrip. Teleport 10 ft; 5-ft ink cloud until your next turn."],["Hearthhiss","Cantrip. Adjacent 5-ft cube {t}; DC {dc} Dex or {d} {t}."]],
  "1st–2nd":[["Chain of Binding Light","Restrain one creature (DC {dc} Str ends); 1 min, conc."],["Surge of Mending Ash","Touch: heal {D}; end disease or poisoned."],["Howl of the Split Sky","15-ft cone; DC {dc} Con: {D} thunder + deafened 1 round (half dmg ok)."],["Veil of Borrowed Night","You + allies in 10 ft invisible until attack/cast or 1 min."],["Thornstep Gate","Teleport 30 ft; creatures in 5 ft of start/end take {d} piercing."]],
  "3rd–4th":[["Sunder the False Wall","20-ft radius/60 ft; DC {dc} Dex: {D} force (objects double)."],["Covenant of Shared Breath","Up to 6 in 30 ft regain {D} HP + temp HP (level or 10)."],["Mirror of Hungry Steps","3 duplicates; destroyer takes {d} psychic."],["Saltfire Brand","Spell attack: {D} {t}; attacks vs target have advantage until your next turn."],["Quiet of the Deep Vault","30-ft silence; chosen creatures immune to thunder. Conc. 10 min."]],
  "5th–6th":[["Crown of Living Storms","1 min: spell attack hits add {d} lightning."],["Unmake the Binding","End ≤5th-level spell, or contest higher (DC {dc})."],["Procession of Iron Ghosts","2 specters (AC16, 30 HP, +{atk}, {d} force) 1 min."],["Heart of the Mountain Gate","Wall of stone — or seal a doorway (DC {dc})."],["Bloom of Severed Fate","Force a save reroll; DC {dc} Cha resists."]],
  "7th–9th":[["Edict of the Last Bell","Enemies in 30 ft: DC {dc} Wis or drop to 0 if <50 HP; else {D} radiant."],["Road That Was Never Built","Teleport you + 8 willing up to 100 miles to a seen place."],["Ashen Starfall","40-ft radius/120 ft; DC {dc} Dex: {D} {t}+{d} bludgeoning."],["Name Written in Sunrise","Revive creature dead ≤24h with 1 HP, no exhaustion."],["Throne of Borrowed Time","Extra turn now; then 1 exhaustion. Scroll burns."]]
};
function scrollItem(r,s){const [n,m]=pick(SCR[s.sp]||SCR.cantrip);const atk=3+s.b+(r==="Legendary"?2:r==="Very Rare"?1:0);return{name:"Scroll of "+n,slot:"Scroll",attune:false,mechanics:fill("Scroll (single use, homebrew). Action. DC {dc}; attack +{atk}. "+m+" Then crumbles.",{dc:s.dc,atk,d:s.d,D:s.D,t:pick(DMG)})};}
const POT=[["Vigor","Action. Regain {D} HP; advantage on Str checks 1 min."],["Clarity","Bonus action. End charmed/frightened; Wis save advantage 10 min."],["Rush","Bonus action. +20 ft & Dash as bonus action 1 min; then −10 ft 1 min."],["Ironhide","Action. {D} temp HP + resist nonmagical B/P/S 10 min."],["Vanish","Bonus action. Invisible 1 min or until attack/cast."],["Dragonbreath","Action. 15-ft cone {t}; DC {dc} Dex: {D} {t} (half ok)."],["Night-Eye","Action. Darkvision 60 ft (or +60) 1 hour."],["Stoneblood","Action. Immune petrified, +2 AC, −10 ft 10 min."],["Heroism","Action. {d} temp HP at start of each turn for 1 min."],["Spellfuel","Action. Regain one slot of {sp} tier or lower (DM call)."]];
const TIN=[["Mint","Bonus action. Heal {d} HP. No other tincture 1 min."],["Bitterroot","Bonus action. Advantage on next Con save within 10 min."],["Foxglove","Bonus action. +10 ft walk for 1 round."],["Smokeleaf","Bonus action. +5 min breath-hold; Stealth advantage next check 10 min."],["Riverglint","Bonus action. End nonmagical poisoned."],["Embertea","Bonus action. Resist cold until end of next turn."],["Moonnectar","Bonus action. Insight advantage 10 min."],["Thornhoney","Bonus action. Next weapon hit within 1 min +{d} poison."],["Saltvein","Bonus action. {d} temp HP 10 min (no self-stack)."],["Quietbark","Bonus action. Stealth vs hearing advantage 10 min."]];
function potionItem(r,s){const[n,m]=pick(POT);return{name:"Potion of "+pick(ADJ)+" "+n,slot:"Potion",attune:false,mechanics:"Potion (consumable, homebrew). "+fill(m,{d:s.d,D:s.D,dc:s.dc,t:pick(DMG),sp:s.sp})};}
function tinctureItem(r,s){const[n,m]=pick(TIN);return{name:"Tincture of "+pick(ADJ)+" "+n,slot:"Tincture",attune:false,mechanics:"Tincture (consumable, homebrew — lighter/shorter than a potion). "+fill(m,{d:s.d,D:s.D,dc:s.dc,t:pick(DMG)})};}
function generate(rarity,type){const s=S[rarity];let item;if(type==="Scroll")item=scrollItem(rarity,s);else if(type==="Potion")item=potionItem(rarity,s);else if(type==="Tincture")item=tinctureItem(rarity,s);else{const at=attune(rarity,s);item={name:nameOf(type),slot:SL[type],attune:!!at.trim(),mechanics:gearFx(type,rarity,s)};}return{name:item.name,rarity,type,slot:item.slot,mechanics:item.mechanics,lore:pick(LORE),attune:!!item.attune};}
let selR=null,selT=null;
const re=document.getElementById("rarities"),te=document.getElementById("types"),btn=document.getElementById("create"),hint=document.getElementById("hint"),res=document.getElementById("result");
function sync(){const ok=!!(selR&&selT);btn.disabled=!ok;hint.textContent=!selR&&!selT?"Pick a rarity and a type":!selR?"Pick a rarity":!selT?"Pick a type":"Ready — tap Create";}
R.forEach(r=>{const b=document.createElement("button");b.type="button";b.className="btn "+(RC[r]||"");b.textContent=r;b.onclick=()=>{selR=r;re.querySelectorAll(".btn").forEach(x=>x.classList.toggle("active",x.textContent===r));sync();};re.appendChild(b);});
T.forEach(t=>{const b=document.createElement("button");b.type="button";b.className="btn type";b.textContent=t;b.onclick=()=>{selT=t;te.querySelectorAll(".btn").forEach(x=>x.classList.toggle("active",x.textContent===t));sync();};te.appendChild(b);});
const esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
btn.onclick=()=>{if(!selR||!selT)return;const item=generate(selR,selT);res.classList.remove("empty");res.classList.remove("flash");void res.offsetWidth;res.classList.add("flash");const chips=['<span class="chip rarity">'+esc(item.rarity)+'</span>','<span class="chip slot">'+esc(item.slot)+'</span>','<span class="chip">Homebrew</span>'];if(item.attune)chips.push('<span class="chip attune">Attunement</span>');res.innerHTML='<h2 class="item-name">'+esc(item.name)+'</h2><div class="meta-row">'+chips.join("")+'</div><p class="block-label">Table-ready mechanics</p><p class="mechanics">'+esc(item.mechanics)+'</p><p class="block-label">Lore</p><p class="lore">'+esc(item.lore)+'</p>';};
sync();
})();
